openapi: 3.0.1
info:
  title: ContextTest
  description: API Definition of ContextTest
  version: 1.0.0
servers:
- url: http://localhost:8290/contexttest
paths:
  /try:
    get:
      responses:
        default:
          description: Default response
